// Generated by scripts/generate-cli.mjs. Do not edit.
// JSON is an untrusted boundary; these generated predicates validate every input field.
/* oxlint-disable anti-slop/no-unknown-parameters, anti-slop/no-runtime-typeof */
import {
	listHeartbeats,
	getHeartbeat,
	createHeartbeat,
	updateHeartbeat,
	deleteHeartbeat,
} from "@onlineornot/api";
import type {
	CreateHeartbeatData,
	UpdateHeartbeatData,
} from "@onlineornot/api";

import { unwrapApiEnvelope } from "../api/infrastructure";
import { authenticatedConfig, isBodyObject, readInput } from "../cli-runtime";
import { logger } from "../logger";
import type { CommonYargsArgv } from "../yargs-types";
import manifest from "./heartbeats.manifest.json";
const metadata = [
	{
		options: {
			json: { type: "boolean", describe: "Return the API envelope as JSON" },
			page: {
				type: "number",
				describe: "Page number (one page per invocation)",
			},
			"per-page": { type: "number", describe: "Number of items per page" },
		},
	},
	{
		options: {
			json: { type: "boolean", describe: "Return the API envelope as JSON" },
		},
	},
	{
		options: {
			json: { type: "boolean", describe: "Return the API envelope as JSON" },
			input: {
				type: "string",
				demandOption: true,
				describe: "JSON file, or - for stdin (no body flags; never merged)",
				nargs: 1,
			},
		},
	},
	{
		options: {
			json: { type: "boolean", describe: "Return the API envelope as JSON" },
			input: {
				type: "string",
				demandOption: true,
				describe: "JSON file, or - for stdin (no body flags; never merged)",
				nargs: 1,
			},
		},
	},
	{
		options: {
			json: { type: "boolean", describe: "Return the API envelope as JSON" },
			yes: {
				type: "boolean",
				describe:
					"Confirm permanent deletion (required, including noninteractive use)",
			},
		},
	},
] as const;
function isCreateHeartbeatDataBody(
	value: unknown,
): value is CreateHeartbeatData["body"] {
	return (
		isBodyObject(value) &&
		Object.keys(value).every((key) =>
			[
				"name",
				"report_period",
				"report_period_cron",
				"timezone",
				"grace_period",
				"reminder_alert_interval_minutes",
				"user_alerts",
				"slack_alerts",
				"discord_alerts",
				"webhook_alerts",
				"oncall_alerts",
				"incident_io_alerts",
				"microsoft_teams_alerts",
				"telegram_alerts",
				"pushover_alerts",
				"alert_priority",
			].includes(key),
		) &&
		typeof value["name"] === "string" &&
		(value["report_period"] === undefined ||
			(typeof value["report_period"] === "number" &&
				Number.isInteger(value["report_period"]) &&
				value["report_period"] >= 1)) &&
		(value["report_period_cron"] === undefined ||
			typeof value["report_period_cron"] === "string") &&
		(value["timezone"] === undefined ||
			typeof value["timezone"] === "string") &&
		typeof value["grace_period"] === "number" &&
		Number.isInteger(value["grace_period"]) &&
		value["grace_period"] >= 1 &&
		(value["reminder_alert_interval_minutes"] === undefined ||
			(typeof value["reminder_alert_interval_minutes"] === "number" &&
				Number.isInteger(value["reminder_alert_interval_minutes"]) &&
				value["reminder_alert_interval_minutes"] >= -1)) &&
		(value["user_alerts"] === undefined ||
			(Array.isArray(value["user_alerts"]) &&
				value["user_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["slack_alerts"] === undefined ||
			(Array.isArray(value["slack_alerts"]) &&
				value["slack_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["discord_alerts"] === undefined ||
			(Array.isArray(value["discord_alerts"]) &&
				value["discord_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["webhook_alerts"] === undefined ||
			(Array.isArray(value["webhook_alerts"]) &&
				value["webhook_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["oncall_alerts"] === undefined ||
			(Array.isArray(value["oncall_alerts"]) &&
				value["oncall_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["incident_io_alerts"] === undefined ||
			(Array.isArray(value["incident_io_alerts"]) &&
				value["incident_io_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["microsoft_teams_alerts"] === undefined ||
			(Array.isArray(value["microsoft_teams_alerts"]) &&
				value["microsoft_teams_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["telegram_alerts"] === undefined ||
			(Array.isArray(value["telegram_alerts"]) &&
				value["telegram_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["pushover_alerts"] === undefined ||
			(Array.isArray(value["pushover_alerts"]) &&
				value["pushover_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["alert_priority"] === undefined ||
			(typeof value["alert_priority"] === "string" &&
				(value["alert_priority"] === "LOW" ||
					value["alert_priority"] === "HIGH")))
	);
}
function isUpdateHeartbeatDataBody(
	value: unknown,
): value is UpdateHeartbeatData["body"] {
	return (
		isBodyObject(value) &&
		Object.keys(value).every((key) =>
			[
				"name",
				"report_period",
				"report_period_cron",
				"timezone",
				"grace_period",
				"reminder_alert_interval_minutes",
				"user_alerts",
				"slack_alerts",
				"discord_alerts",
				"webhook_alerts",
				"oncall_alerts",
				"incident_io_alerts",
				"microsoft_teams_alerts",
				"telegram_alerts",
				"pushover_alerts",
				"alert_priority",
				"paused",
				"muted",
			].includes(key),
		) &&
		(value["name"] === undefined || typeof value["name"] === "string") &&
		(value["report_period"] === undefined ||
			(typeof value["report_period"] === "number" &&
				Number.isInteger(value["report_period"]) &&
				value["report_period"] >= 1) ||
			value["report_period"] === null) &&
		(value["report_period_cron"] === undefined ||
			typeof value["report_period_cron"] === "string" ||
			value["report_period_cron"] === null) &&
		(value["timezone"] === undefined ||
			typeof value["timezone"] === "string" ||
			value["timezone"] === null) &&
		(value["grace_period"] === undefined ||
			(typeof value["grace_period"] === "number" &&
				Number.isInteger(value["grace_period"]) &&
				value["grace_period"] >= 1)) &&
		(value["reminder_alert_interval_minutes"] === undefined ||
			(typeof value["reminder_alert_interval_minutes"] === "number" &&
				Number.isInteger(value["reminder_alert_interval_minutes"]) &&
				value["reminder_alert_interval_minutes"] >= -1)) &&
		(value["user_alerts"] === undefined ||
			(Array.isArray(value["user_alerts"]) &&
				value["user_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["slack_alerts"] === undefined ||
			(Array.isArray(value["slack_alerts"]) &&
				value["slack_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["discord_alerts"] === undefined ||
			(Array.isArray(value["discord_alerts"]) &&
				value["discord_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["webhook_alerts"] === undefined ||
			(Array.isArray(value["webhook_alerts"]) &&
				value["webhook_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["oncall_alerts"] === undefined ||
			(Array.isArray(value["oncall_alerts"]) &&
				value["oncall_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["incident_io_alerts"] === undefined ||
			(Array.isArray(value["incident_io_alerts"]) &&
				value["incident_io_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["microsoft_teams_alerts"] === undefined ||
			(Array.isArray(value["microsoft_teams_alerts"]) &&
				value["microsoft_teams_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["telegram_alerts"] === undefined ||
			(Array.isArray(value["telegram_alerts"]) &&
				value["telegram_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["pushover_alerts"] === undefined ||
			(Array.isArray(value["pushover_alerts"]) &&
				value["pushover_alerts"].every(
					(item: unknown) => typeof item === "string",
				))) &&
		(value["alert_priority"] === undefined ||
			(typeof value["alert_priority"] === "string" &&
				(value["alert_priority"] === "LOW" ||
					value["alert_priority"] === "HIGH"))) &&
		(value["paused"] === undefined || typeof value["paused"] === "boolean") &&
		(value["muted"] === undefined || typeof value["muted"] === "boolean")
	);
}
export function registerCommands(yargs: CommonYargsArgv) {
	logger.loggerLevel = "log";
	yargs.parserConfiguration({ "duplicate-arguments-array": true });
	yargs.command(
		"list",
		"List all heartbeats",
		(y) => {
			const options = y.options(metadata[0].options);
			return options;
		},
		async (args) => {
			if (
				args["page"] !== undefined &&
				!(
					typeof args["page"] === "number" &&
					Number.isInteger(args["page"]) &&
					args["page"] >= 1
				)
			)
				throw new Error("Invalid --page");
			if (
				args["per-page"] !== undefined &&
				!(
					typeof args["per-page"] === "number" &&
					Number.isInteger(args["per-page"]) &&
					args["per-page"] >= 1
				)
			)
				throw new Error("Invalid --per-page");
			if (!args.json)
				logger.warn(
					"heartbeats management commands are experimental; use --json for automation.",
				);
			const config = await authenticatedConfig();
			const envelope = unwrapApiEnvelope(
				await listHeartbeats({
					...config,
					query: { page: args["page"], per_page: args["per-page"] },
				}),
				"/v1/heartbeats",
			);
			logger.log(JSON.stringify(envelope, null, 2));
		},
	);
	yargs.command(
		"view <id>",
		"Retrieve a heartbeat",
		(y) => {
			const options = y.options(metadata[1].options);
			return options.positional("id", {
				type: "string",
				demandOption: true,
				describe: "Heartbeat ID",
			});
		},
		async (args) => {
			if (!(typeof args["id"] === "string" && args["id"].length >= 8))
				throw new Error("Invalid id");
			if (!args.json)
				logger.warn(
					"heartbeats management commands are experimental; use --json for automation.",
				);
			const config = await authenticatedConfig();
			const envelope = unwrapApiEnvelope(
				await getHeartbeat({ ...config, path: { heartbeat_id: args["id"] } }),
				"/v1/heartbeats/{heartbeat_id}",
			);
			logger.log(JSON.stringify(envelope, null, 2));
		},
	);
	yargs.command(
		"create",
		"Create a heartbeat.",
		(y) => {
			const options = y.options(metadata[2].options);
			return options;
		},
		async (args) => {
			const text = await readInput(args.input);
			let body: unknown;
			try {
				body = JSON.parse(text);
			} catch {
				throw new Error("Invalid JSON input; expected an object.");
			}
			if (!isCreateHeartbeatDataBody(body))
				throw new Error(
					"Invalid JSON body; see heartbeats commands for the pinned input contract.",
				);
			if (!args.json)
				logger.warn(
					"heartbeats management commands are experimental; use --json for automation.",
				);
			const config = await authenticatedConfig();
			const envelope = unwrapApiEnvelope(
				await createHeartbeat({ ...config, body }),
				"/v1/heartbeats",
			);
			logger.log(JSON.stringify(envelope, null, 2));
		},
	);
	yargs.command(
		"update <id>",
		"Update a heartbeat.",
		(y) => {
			const options = y.options(metadata[3].options);
			return options.positional("id", {
				type: "string",
				demandOption: true,
				describe: "Heartbeat ID",
			});
		},
		async (args) => {
			if (!(typeof args["id"] === "string" && args["id"].length >= 8))
				throw new Error("Invalid id");
			const text = await readInput(args.input);
			let body: unknown;
			try {
				body = JSON.parse(text);
			} catch {
				throw new Error("Invalid JSON input; expected an object.");
			}
			if (!isUpdateHeartbeatDataBody(body))
				throw new Error(
					"Invalid JSON body; see heartbeats commands for the pinned input contract.",
				);
			if (!args.json)
				logger.warn(
					"heartbeats management commands are experimental; use --json for automation.",
				);
			const config = await authenticatedConfig();
			const envelope = unwrapApiEnvelope(
				await updateHeartbeat({
					...config,
					path: { heartbeat_id: args["id"] },
					body,
				}),
				"/v1/heartbeats/{heartbeat_id}",
			);
			logger.log(JSON.stringify(envelope, null, 2));
		},
	);
	yargs.command(
		"delete <id>",
		"Delete a heartbeat",
		(y) => {
			const options = y.options(metadata[4].options);
			return options.positional("id", {
				type: "string",
				demandOption: true,
				describe: "Heartbeat ID",
			});
		},
		async (args) => {
			if (!(typeof args["id"] === "string" && args["id"].length >= 8))
				throw new Error("Invalid id");
			if (args.yes !== true)
				throw new Error(
					"Deletion or destructive mutation requires --yes; no request was sent.",
				);
			if (!args.json)
				logger.warn(
					"heartbeats management commands are experimental; use --json for automation.",
				);
			const config = await authenticatedConfig();
			const envelope = unwrapApiEnvelope(
				await deleteHeartbeat({
					...config,
					path: { heartbeat_id: args["id"] },
				}),
				"/v1/heartbeats/{heartbeat_id}",
			);
			logger.log(JSON.stringify(envelope, null, 2));
		},
	);
	return yargs
		.command(
			"commands",
			"Show the pinned heartbeats command and input contract",
			(y) => y.option("json", { type: "boolean" }),
			() => logger.log(JSON.stringify(manifest, null, 2)),
		)
		.demandCommand(1)
		.strict();
}
