// Generated by scripts/generate-cli.mjs. Do not edit.
import type { CommonYargsArgv } from "../yargs-types";
import { registerCommands as resource0 } from "./heartbeats";
const resources = ["heartbeats"] as const;
export function isGeneratedCommand(argv: string[]): boolean {
	const command = argv.find((arg) => !arg.startsWith("-"));
	return resources.some((resource) => resource === command);
}
export function registerGeneratedCommands(yargs: CommonYargsArgv) {
	yargs.command("heartbeats", "Manage heartbeat monitors", resource0);
	return yargs;
}
