name: Create Pull Request Prerelease

on: pull_request

jobs:
  build:
    if: ${{ github.repository_owner == 'onlineornot' }}
    name: Build & Publish a Prerelease to the Adhoc Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Modify package.json version
        run: node .github/version-script.js

      - name: Build
        run: pnpm run build
        env:
          NODE_ENV: "production"

      - name: Pack onlineornot
        run: pnpm pack
        working-directory: packages/onlineornot

      - name: Upload packaged onlineornot artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-package-onlineornot-${{ github.event.number }} # encode the PR number into the artifact name
          path: packages/onlineornot/onlineornot-*.tgz
