name: Pull Request

on: pull_request

jobs:
  check:
    name: "Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: "npm" # cache ~/.npm in case 'npm ci' needs to run

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check for errors
        run: npm run check
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

  test:
    name: "Tests"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: "npm" # cache ~/.npm in case 'npm ci' needs to run

      - name: Install NPM Dependencies
        run: npm ci

      - name: Run builds
        run: npm run build
        env:
          NODE_ENV: "production"

      - name: Run tests & collect coverage
        run: npm run test:ci
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
